In [3]:
import numpy as np 
import matplotlib.pyplot as plt 
import string 
from sklearn.model_selection import train_test_split

In [4]:
archivos = ["./07-data/poemas_Benedetti.txt","./07-data/poemas_pablo_neruda.txt"]

In [5]:
textos = []
etiquetas = []

In [11]:
for etiqueta, indice in enumerate(archivos):
    print(f"{indice} Corresponde a {etiqueta}")
    
    with open(indice, "r", encoding="utf-8") as archivo:
        # Abrir y Recorrer cada archivo
        for line in archivo:
            # Recorrer cada Linea del archivo
            print(line)
            # Eliminar espacios blancos de la derecha y convertir en minúsculas
            line = line.rstrip().lower()
            print(line)
            if line:
                # Eliminar puntuación
                line = line.translate(str.maketrans("","", string.punctuation))
                textos.append(line)
                etiquetas.append(etiqueta)
            print(line)

./07-data/poemas_Benedetti.txt Corresponde a 0
Poemas varios

poemas varios
poemas varios
Mario Benedetti

mario benedetti
mario benedetti
La buena tiniebla

la buena tiniebla
la buena tiniebla
Una mujer desnuda y en lo oscuro

una mujer desnuda y en lo oscuro
una mujer desnuda y en lo oscuro
genera un resplandor que da confianza

genera un resplandor que da confianza
genera un resplandor que da confianza
de modo que si sobreviene

de modo que si sobreviene
de modo que si sobreviene
un apagón o un desconsuelo

un apagón o un desconsuelo
un apagón o un desconsuelo
es conveniente y hasta imprescindible

es conveniente y hasta imprescindible
es conveniente y hasta imprescindible
tener a mano una mujer desnuda

tener a mano una mujer desnuda
tener a mano una mujer desnuda
entonces las paredes se acuarelan

entonces las paredes se acuarelan
entonces las paredes se acuarelan
el cielo raso se convierte en cielo

el cielo raso se convierte en cielo
el cielo raso se convierte en cielo
las telar

In [12]:
textos

['poemas varios',
 'mario benedetti',
 'la buena tiniebla',
 'una mujer desnuda y en lo oscuro',
 'genera un resplandor que da confianza',
 'de modo que si sobreviene',
 'un apagón o un desconsuelo',
 'es conveniente y hasta imprescindible',
 'tener a mano una mujer desnuda',
 'entonces las paredes se acuarelan',
 'el cielo raso se convierte en cielo',
 'las telarañas vibran en su ángulo',
 'los almanaques dominguean',
 'y los ojos felices y felinos',
 'miran y no se cansan de mirar',
 'una mujer desnuda y en lo oscuro',
 'una mujer querida o a querer',
 'exorcisa por una vez la muerte',
 'preliminar del miedo',
 'por sobre las terrazas alunadas',
 'donde se aman cautelosamente los gatos',
 'y los brillos esquivan las chimeneas',
 'creo que nadie sabe lo que yo sé esta noche',
 'algo aprendido a pedacitos y a pulsaciones',
 'y que integra mi pánico tradicional modesto',
 '¿cómo desmenuzar plácidamente el miedo',
 'comprender por fin que no es una excusa',
 'sino un escalofrío parecido 

In [13]:
etiquetas

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [14]:
train_text, test_text, Ytrain, Ytest = train_test_split(textos, etiquetas, test_size=0.1, random_state=42)

In [15]:
len(Ytrain), len(Ytest)

(1776, 198)

In [20]:
"""
"<unk>" es una convención que se utiliza a menudo en el procesamiento de lenguaje natural para representar palabras desconocidas o fuera del vocabulario. En este caso, se está asignando el índice 0 a esta palabra especial.
"""
indice = 1
indicepalabras = {'<unk>': 0}

In [21]:
# Construcción de un Diccionario de Codificación de Palabras a Índice
for texto in train_text:
    tokens = texto.split()
    for token in tokens:
        if token not in indicepalabras:
            indicepalabras[token] = indice
            indice += 1

In [22]:
indicepalabras

{'<unk>': 0,
 'no': 1,
 'congeles': 2,
 'el': 3,
 'júbilo': 4,
 'nosotros': 5,
 'mantuvimos': 6,
 'nuestras': 7,
 'voces': 8,
 'o': 9,
 'sea': 10,
 'mi': 11,
 'alma': 12,
 'se': 13,
 'contenta': 14,
 'con': 15,
 'haberla': 16,
 'perdido': 17,
 'sé': 18,
 'cómo': 19,
 'ni': 20,
 'y': 21,
 'una': 22,
 'veta': 23,
 'de': 24,
 'amor': 25,
 'a': 26,
 'solas': 27,
 'su': 28,
 'suerte': 29,
 'aquí': 30,
 'te': 31,
 'amo': 32,
 'por': 33,
 'eso': 34,
 'barata': 35,
 'la': 36,
 'función': 37,
 'diciendo': 38,
 'qué': 39,
 'palabras': 40,
 'claro': 41,
 'que': 42,
 'soledad': 43,
 'viene': 44,
 'sola': 45,
 'también': 46,
 'hubo': 47,
 'un': 48,
 'cuaderno': 49,
 'figuras': 50,
 'tu': 51,
 'regreso': 52,
 'tiene': 53,
 'tanto': 54,
 'verdor': 55,
 'perecido': 56,
 'uno': 57,
 'siente': 58,
 'lluvia': 59,
 'llanto': 60,
 'suele': 61,
 'desplegarse': 62,
 'ante': 63,
 'indefensos': 64,
 'noches': 65,
 'deseos': 66,
 'quizá': 67,
 'salga': 68,
 'enseguida': 69,
 'sol': 70,
 'salvaje': 71,
 'nombre'

In [23]:
len(indicepalabras)

2692

In [24]:
train_text_int = []
test_text_int = []

In [25]:
for texto in train_text:
    tokens = texto.split()
    linea_entero = [indicepalabras[token] for token in tokens]
    train_text_int.append(linea_entero)

In [26]:
train_text_int

[[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10],
 [11, 12, 1, 13, 14, 15, 16, 17],
 [1, 18, 19, 20, 18],
 [21, 22, 23, 24, 25],
 [26, 27, 15, 28, 29],
 [1, 18, 19, 20, 18],
 [30, 31, 32],
 [33, 34],
 [35, 36, 37],
 [38, 39, 40],
 [41, 42, 36, 43, 1, 44, 45],
 [46, 47, 48, 49, 24, 50],
 [51, 52, 53, 54],
 [3, 55, 56],
 [57, 13, 58],
 [36, 59, 15, 3, 60],
 [42, 61, 62, 63, 64],
 [24, 65, 21, 66],
 [21, 67, 33, 34, 68, 69, 3, 70],
 [26, 11, 12, 45, 21, 71, 26, 11, 72, 42, 73, 74],
 [24, 51, 75],
 [76, 28, 55],
 [77, 78, 79],
 [36, 80, 42, 13, 81, 21, 1, 82],
 [83, 84, 26, 85, 86],
 [87],
 [88, 89, 22, 90],
 [91, 92, 93, 94, 95, 96, 97, 98],
 [20, 99, 22, 100, 9, 22, 101],
 [102, 3, 103],
 [21, 104, 105, 92, 106, 107, 24, 85, 108],
 [33, 109],
 [110, 111, 112, 113, 114, 21, 113, 115],
 [116, 117, 42, 118, 119, 26, 120, 121, 42, 122, 1, 123, 124, 20, 125, 126],
 [127, 128, 129, 15, 130, 93, 40, 24, 131],
 [132],
 [36, 133, 134, 42, 135, 36, 136],
 [137, 42, 83, 138],
 [139, 24, 140, 141, 51, 12],
 [

In [27]:
for texto in test_text:
    tokens = texto.split()
    # Con get se intenta obtener el valor de la clave token del diccionario indicepalabras, si no existe, se retorna 0
    line_as_int = [indicepalabras.get(token,0) for token in tokens]
    test_text_int.append(line_as_int)

In [28]:
test_text_int

[[944, 944, 0, 0, 92, 1330, 24, 80],
 [283, 111, 42, 155, 1295, 0, 42, 0],
 [21, 51, 60, 33, 3, 548],
 [260, 210, 0, 0],
 [2062, 329, 21, 253, 360, 42, 1, 0, 329],
 [203, 104],
 [83, 1206, 233, 9, 1023, 0, 685],
 [353],
 [0, 0, 15, 36, 217],
 [21, 0, 113, 548],
 [21, 122, 83, 222, 690, 248],
 [1916, 1917, 3, 1392],
 [277, 0, 48, 943, 0],
 [22, 2001, 255],
 [450, 1521, 15, 3, 70, 78, 15, 48, 0],
 [15, 116, 1016, 391, 142, 0],
 [1, 301, 485],
 [1564, 26, 1021, 0],
 [92, 422, 2600, 112, 179, 15, 297, 1347],
 [42, 122, 0, 0, 26, 1248],
 [0, 1244],
 [0, 24, 672],
 [1, 31, 0, 142, 430],
 [135, 252, 950],
 [260, 1, 18, 884, 201],
 [0],
 [141, 42, 116, 1451, 0, 26, 116, 0, 13, 0, 116, 0, 24],
 [0, 113, 0],
 [42, 422, 3, 548, 371, 0],
 [24, 93, 0, 0, 21, 24, 116, 0],
 [21, 3, 0, 24, 500, 502],
 [1629, 0],
 [147, 48, 1446, 1447],
 [301, 0],
 [155, 1085, 41],
 [1855, 353],
 [1561, 1, 463, 887],
 [111, 0, 21, 0],
 [21, 48, 612, 13, 689, 26, 744, 92, 233],
 [11, 666, 135],
 [42, 0, 157, 190],
 [104

In [31]:
V = len(indicepalabras)
# Creamos una matriz de 1 con las mismas dimensiones que V, con (2692) filas y (2692) columnas
# Las A Representan la Matriz de Transición
A0 = np.ones((V,V)) 
A1 = np.ones((V,V))
# Y tambien vamos a hacer un vector con (2692) dimensiones
# Las pi Representan las probabilidades iniciales de las palabras
pi0 = np.ones(V) 
pi1 = np.ones(V)

In [32]:
A0

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [33]:
pi0

array([1., 1., 1., ..., 1., 1., 1.])

In [34]:
def compute_counts(text_as_int, A, pi):
    for tokens in text_as_int:
        last_idx = None
        for idx in tokens:
            # Estamos en la primera palabra de la secuencia
            if last_idx is None:
                pi[idx] += 1 # Aumentamos la probabilidad de la palabra en la primera palabra de la secuencia
            else:
                A[last_idx,idx] += 1 # Aumentamos la probabilidad de la palabra en la palabra previa
            last_idx = idx

In [35]:
compute_counts([t for t, y in zip(train_text_int, Ytrain) if y == 0], A0, pi0)
compute_counts([t for t, y in zip(train_text_int, Ytrain) if y == 1], A1, pi1)

In [36]:
pi0

array([ 1., 45.,  1., ...,  1.,  1.,  1.])

In [39]:
pi1

array([1., 1., 1., ..., 1., 1., 1.])

In [38]:
A0

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 2., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [40]:
# Normaliza A y pi para que sean matrices de probabilidad válidas
# Convencete de que esto es equivalente a las fórmulas mostradas anteriormente
A0 /= A0.sum(axis=1, keepdims=True)
pi0 /= pi0.sum()

A1 /= A1.sum(axis=1, keepdims=True)
pi1 /= pi1.sum()

In [41]:
pi0

array([0.00024907, 0.01120797, 0.00024907, ..., 0.00024907, 0.00024907,
       0.00024907])

In [42]:
pi1

array([0.00031797, 0.00031797, 0.00031797, ..., 0.00031797, 0.00031797,
       0.00031797])

In [43]:
A0

array([[0.00037147, 0.00037147, 0.00037147, ..., 0.00037147, 0.00037147,
        0.00037147],
       [0.00035348, 0.00035348, 0.00070696, ..., 0.00035348, 0.00035348,
        0.00035348],
       [0.00037133, 0.00037133, 0.00037133, ..., 0.00037133, 0.00037133,
        0.00037133],
       ...,
       [0.00037133, 0.00037133, 0.00037133, ..., 0.00037133, 0.00037133,
        0.00037133],
       [0.00037147, 0.00037147, 0.00037147, ..., 0.00037147, 0.00037147,
        0.00037147],
       [0.00037133, 0.00037133, 0.00037133, ..., 0.00037133, 0.00037133,
        0.00037133]])

In [44]:
# Calcula el logaritmo de A y pi, ya que no necesitamos las probabilidades reales
logA0 = np.log(A0)
logpi0 = np.log(pi0)

logA1 = np.log(A1)
logpi1 = np.log(pi1)

In [45]:
logpi0

array([-8.29779263, -4.49113014, -8.29779263, ..., -8.29779263,
       -8.29779263, -8.29779263])

In [46]:
logA0

array([[-7.89803969, -7.89803969, -7.89803969, ..., -7.89803969,
        -7.89803969, -7.89803969],
       [-7.94767857, -7.94767857, -7.25453139, ..., -7.94767857,
        -7.94767857, -7.94767857],
       [-7.89841109, -7.89841109, -7.89841109, ..., -7.89841109,
        -7.89841109, -7.89841109],
       ...,
       [-7.89841109, -7.89841109, -7.89841109, ..., -7.89841109,
        -7.89841109, -7.89841109],
       [-7.89803969, -7.89803969, -7.89803969, ..., -7.89803969,
        -7.89803969, -7.89803969],
       [-7.89841109, -7.89841109, -7.89841109, ..., -7.89841109,
        -7.89841109, -7.89841109]])

In [47]:
count0 = sum(y == 0 for y in Ytrain) # Cuenta de etiquetas de clase 0 en Ytrain
count1 = sum(y == 1 for y in Ytrain) # Cuenta de etiquetas de clase 1 en Ytrain
total = len(Ytrain) # Cantidad total de ejemplos de entrenamiento
p0 = count0 / total # Probabilidad a priori de clase 0
p1 = count1 / total # Probabilidad a priori de clase 1
logp0 = np.log(p0) # Logaritmo de la probabilidad a priori de clase 0
logp1 = np.log(p1) # Logaritmo de la probabilidad a priori de clase 1
p0, p1 # Imprime las probabilidades a priori de ambas clases

(0.7449324324324325, 0.25506756756756754)

In [57]:
# Construccion de un clasificador
class Classifier:
    def __init__(self, logAs, logpis, logpriors):
        self.logAs = logAs
        self.logpis = logpis
        self.logpriors = logpriors
        self.k = len(logpriors) # número de clases
    
    def _compute_log_likelihood(self, input_, class_):
        logA = self.logAs[class_]
        logpi = self.logpis[class_]
        
        last_idx = None
        logprob = 0
        for idx in input_:
            if last_idx is None:
                # Es el primer token en la secuencia
                logprob += logpi[idx]
            else:
                # Calcula la probabilidad de transición de la palabra amnterior a la actual
                logprob += logA[last_idx, idx]
                
            # Actualiza last_idx para la próxima iteración
            last_idx = idx
        return logprob
    
    def predict(self, inputs):
        predictions = np.zeros(len(inputs))
        for i, input_ in enumerate(inputs):
            # Calcula los logaritmos de las probabilidades posteriores para cada clase
            posteriors = [self._compute_log_likelihood(input_, c) + self.logpriors[c] for c in range(self.k)]
            
            # Elige la clase con la mayor probabilidad posterior como la predicción
            pred = np.argmax(posteriors)
            predictions[i] = pred
        return predictions

In [58]:
# Cada arreglo debe estar en orden ya que se asume que las clases indexan estas listas
clf = Classifier([logA0, logA1], [logpi0, logpi1], [logp0, logp1])

In [60]:
Ptrain = clf.predict(train_text_int)
print(f"Train acc: {np.mean(Ptrain == Ytrain)}")

Train acc: 0.9915540540540541


In [61]:
Ptest = clf.predict(test_text_int)
print(f"Test acc: {np.mean(Ptest == Ytest)}")

Test acc: 0.8333333333333334
